- !!python/object:profiles.Profile
  name: Ping localhost
  profile_id: 1
  provider_id: PingProvider
  provider_parameters:
    Target: 'localhost'
    ThresholdMs: '2'
  run_every_x_seconds: 1
- !!python/object:profiles.Profile
  name: Ping Google
  profile_id: 2
  provider_id: PingProvider
  provider_parameters:
    Target: 'google.com'
    ThresholdMs: '20'
  run_every_x_seconds: 5
