- !!python/object:profiles.Profile
  name: ping localhost
  profile_id: 1a3b7926114a4ee28943517199dd4093
  provider_id: PingProviderxx
  provider_parameters:
    Target: 'localhost'
    ThresholdMs: '2'
  run_every_x_seconds: 1
- !!python/object:profiles.Profile
  name: Ping Google
  profile_id: 2a1fd6c6bc8543458ccb48fb3556785e
  provider_id: PingProvider
  provider_parameters:
    Target: 'google.com'
    ThresholdMs: '20'
  run_every_x_seconds: 5
