- !!python/object:pulse.profiles.Profile
  name: ping localhost 1
  profile_id: 1
  provider_id: PingProvider
  provider_parameters:
    Target: 'localhost'
    ThresholdMs: '2'
  run_every_x_seconds: 1
- !!python/object:pulse.profiles.Profile
  name: ping localhost 2
  profile_id: 3
  provider_id: PingProvider
  provider_parameters:
    Target: 'localhost'
    ThresholdMs: '5'
  run_every_x_seconds: 1
- !!python/object:pulse.profiles.Profile
  name: ping Google
  profile_id: 2
  provider_id: PingProvider
  provider_parameters:
    Target: 'google.com'
    ThresholdMs: '20'
  run_every_x_seconds: 5
