- !!python/object:pulse.profiles.Profile
  id: 1fe3fea5f3bc41efa8dd8c9cf0ab2f2b
  name: Profile name goes here (1)
  provider_id: PingProvider
  provider_parameters:
    Common.SampleParameter: '[optional] Example of a common parameter'
    Target: '[required] IP or hostname'
    ThresholdMs: '[required] Threshold (ms)'
  run_every_x_seconds: 10
- !!python/object:pulse.profiles.Profile
  id: 9b6dfb1b53c640cdb94b5fddf28a61b7
  name: Profile name goes here (2)
  provider_id: SampleProvider
  provider_parameters:
    Common.SampleParameter: '[optional] Example of a common parameter'
    SampleParam: '[required] Sample param description'
  run_every_x_seconds: 10
- !!python/object:pulse.profiles.Profile
  id: de02f88fb45b4703a1ea321692ba3f6e
  name: Profile name goes here (3)
  provider_id: PingProvider
  provider_parameters:
    Common.SampleParameter: '[optional] Example of a common parameter'
    Target: '[required] IP or hostname'
    ThresholdMs: '[required] Threshold (ms)'
  run_every_x_seconds: 10
- !!python/object:pulse.profiles.Profile
  id: c4a603e2557c4f4092c330512db140ba
  name: Profile name goes here (4)
  provider_id: SampleProvider
  provider_parameters:
    Common.SampleParameter: '[optional] Example of a common parameter'
    SampleParam: '[required] Sample param description'
  run_every_x_seconds: 10
