- !!python/object:pulse.profiles.Profile
  name: Profile name goes here (1)
  profile_id: 42c493d0f2634c4db85d482873bade8c
  provider_id: PingProvider
  provider_parameters:
    Common.SampleParameter: '[optional] Example of a common parameter'
    Target: '[required] IP or hostname'
    ThresholdMs: '[required] Threshold (ms)'
  run_every_x_seconds: 10
- !!python/object:pulse.profiles.Profile
  name: Profile name goes here (2)
  profile_id: 71175fd8fddd40cdb9744a7295bb1494
  provider_id: SampleProvider
  provider_parameters:
    Common.SampleParameter: '[optional] Example of a common parameter'
    SampleParam: '[required] Sample param description'
  run_every_x_seconds: 10
- !!python/object:pulse.profiles.Profile
  name: Profile name goes here (3)
  profile_id: af9ec3c36fa748eeac75adf425242d8f
  provider_id: PingProvider
  provider_parameters:
    Common.SampleParameter: '[optional] Example of a common parameter'
    Target: '[required] IP or hostname'
    ThresholdMs: '[required] Threshold (ms)'
  run_every_x_seconds: 10
- !!python/object:pulse.profiles.Profile
  name: Profile name goes here (4)
  profile_id: c266a2197a5c475eb33d49284f1ca5e5
  provider_id: SampleProvider
  provider_parameters:
    Common.SampleParameter: '[optional] Example of a common parameter'
    SampleParam: '[required] Sample param description'
  run_every_x_seconds: 10
